set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(ARM_COMPILE_OPTION "-mcpu=cortex-a55 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security")

set(CMAKE_SYSROOT /opt/rz-vlp/5.0.11/sysroots/cortexa55-poky-linux)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CROSS_COMPILE /opt/rz-vlp/5.0.11/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-)
set(CMAKE_C_COMPILER ${CROSS_COMPILE}gcc)
set(CMAKE_CXX_COMPILER ${CROSS_COMPILE}g++)
set(CMAKE_AR ${CROSS_COMPILE}ar)
set(CMAKE_RANLIB ${CROSS_COMPILE}ranlib)
set(CMAKE_LINKER ${CMAKE_C_COMPILER})

SET (CMAKE_C_COMPILER_WORKS 1)
SET (CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${ARM_COMPILE_OPTION}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ARM_COMPILE_OPTION}")

set(CMAKE_C_COMPILER_WORKS TRUE CACHE INTERNAL "" FORCE)
set(CMAKE_CXX_COMPILER_WORKS TRUE CACHE INTERNAL "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY CACHE STRING "Force static for cross-compiling" FORCE)
set(CMAKE_CROSSCOMPILING TRUE CACHE BOOL "" FORCE)
set(CMAKE_CROSSCOMPILING_EMULATOR "" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")

set(CMAKE_HAVE_PTHREAD_H 1 CACHE INTERNAL "")
set(THREADS_PTHREAD_ARG "0" CACHE STRING "" FORCE)
set(CMAKE_USE_PTHREADS_INIT 1 CACHE INTERNAL "")
set(CMAKE_THREAD_LIBS_INIT "-lpthread" CACHE STRING "" FORCE)
set(THREADS_PREFER_PTHREAD_FLAG ON CACHE BOOL "" FORCE)

INCLUDE_DIRECTORIES("${CMAKE_SYSROOT}/usr/include/c++/13.4.0 ${CMAKE_SYSROOT}/usr/include")
